services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: admin_system
      MYSQL_USER: admin
      MYSQL_password: password
      MYSQL_ROOT_PASSWORD: root_password
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3366:3306"
    volumes:
      - db-mysql-data:/var/lib/mysql
  backend:
    build:
      context: .
      dockerfile: docker/rails/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/app
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - "9999:3000"
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: docker/nextjs/Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
      - frontend-next:/app/.next
    ports:
      - "3999:3000"
    tty: true
    depends_on:
      - db
      - backend

volumes:
  db-mysql-data:
  frontend-node-modules:
  frontend-next:
